### ISSUE TITLE
Atualizar o readme

### ISSUE THREAD

**Issue by bruno3du** [SanX0000/Xwing#2]
Como recomendações é possível adicionar imagens, mais detalhes do projeto, o que você aprendeu com ele, quais foram as dificuldades, adicionar badges e ser criativo para adicionar mais do seu estilo.

**Comment by SanX0000** [comment]
Segui as suas sugestões e dei uma melhorada no readme. Me diga depois se ficou legal. Muito obrigado pela ajuda.
